Simian 1.5.0 including many new features, bug fixes, etc.
git-svn-id: https://simian.googlecode.com/svn/trunk@15 368532df-a33e-f994-cbfd-937b2e4ba68d

diff --git a/postflight b/postflight
--- a/postflight
+++ b/postflight
@@ -22,6 +22,12 @@
 # invoked from CLI
 
 set -e
+set -x 
+
+function die() {
+  echo ERROR "$@" >&2
+  exit 1
+}
 
 export PATH="$PATH:/usr/bin"
 PKG="$1"
@@ -30,28 +36,24 @@ TARGET_PATH="$3"
 RESOURCES="${PKG}/Contents/Resources"
 BASETMPDIR="${TARGET_PATH}/tmp/"
 OSX=$(sw_vers -productVersion | cut -d. -f1-2)
-VERSION="1.0.1"
+VERSION="1.5.0"
 
 ### set up sane logging
 d=$(date '+%Y%m%d%H%M')
-exec 2>&1
 exec 1> "${BASETMPDIR}/postflight.${d}.$$.log"
+exec 2>&1
+echo postflight BEGIN
 
 ### create temp work directory
 TMPDIR=$(mktemp -d ${BASETMPDIR}/postflightXXXXXX)
 ORIGPWD="${PWD}"
-#trap "rm -rf ${TMPDIR}" EXIT
-
+trap "rm -rf ${TMPDIR}" EXIT
 
 ### install supplied eggs, like M2Crypto.
 
-if [ "${OSX}" = "10.6" ] && [ -x "/usr/bin/easy_install-2.6" ]; then
-  EZ="/usr/bin/easy_install-2.6"
-else
-  EZ="/usr/bin/easy_install"
-fi
+EZ="/usr/bin/easy_install"
 
-[ -x "$EZ" ]
+[ -x "${EZ}" ] || die "Cannot execute ${EZ}"
 
 for egg in ${RESOURCES}/*-${OSX}-*.egg ; do
   ${EZ} -N "${egg}"
@@ -78,14 +80,16 @@ cd "${ORIGPWD}"
 
 ### update munki configuration
 
+echo Begin section: Harmless "configuration not found" messages may follow
 server=`python -c "from simian import settings ; print '%s.%s' % (settings.SUBDOMAIN, settings.DOMAIN)"`
 defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL https://${server}
+echo End section
 
 ### small file operations
 
 chmod 750 /etc/simian/ssl/private_keys
 
-for f in /etc/simian/simian.cfg; do
+for f in /etc/simian/{client,common}.cfg; do
   if [ ! -f "${f}" -a -f "${f}+" ]; then
     mv "${f}+" "${f}"
   else
@@ -93,4 +97,10 @@ for f in /etc/simian/simian.cfg; do
   fi
 done
 
+for f in /Library/Launch{Agents,Daemons}/com.googlecode.munki.*.plist; do
+  chown root:wheel "${f}"
+  chmod 644 "${f}"
+done
+
 ### TODO: remove any files unnecessary on clients
+echo postflight END
